# Dockerfile do Redis com senha
FROM redis:latest

# Copia o arquivo de configuração customizado (vamos criar esse abaixo)
COPY config/redis.conf /usr/local/etc/redis/redis.conf

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
